name: practica-quality-check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ 14, 16 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - name: Run tests
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          coverage-comment: ${{github.event_name == 'pull_request'}}
        id: test
